#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app_lucky_number:
#     path: /
#     controller: App\Controller\LuckyController::number
app_logout:
    path: /logout
    methods: GET
